#!/usr/bin/env bash
# Install the decision-call profile into the Hermes on THIS machine (both the Mac and the box hold
# ~/brain and its writer `needs-you-write`). For the Desktop, install it on the BOX: see --box below.
#
#   hermes/profiles/decision-call/install.sh            install / refresh (backs up first)
#   hermes/profiles/decision-call/install.sh --check    show what is installed; change nothing
#   hermes/profiles/decision-call/install.sh --box      install on the box, whose backend the Desktop uses
#
# What it writes, all under ~/.hermes/profiles/decision-call/ (the profile's own home):
#   plugins/decision-call/   the three tools + the turn hook (from hermes/plugins/decision-call)
#   SOUL.md                  the call's instructions (from this directory)
#   config.yaml              generated by profile_config.py: this machine's model block and its
#                            gbrain READ-ONLY allowlist (minus `think`) are COPIED from
#                            ~/.hermes/config.yaml at install time, so no host path or private name
#                            lives in the repo. EVERY vendor platform gets the `decision_call`
#                            toolset only (no terminal, file, browser, code, messaging, memory).
# The previous config.yaml and SOUL.md go to backups/<UTC stamp>/ first.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../../.." && pwd)"
HH="${HERMES_ROOT:-$HOME/.hermes}"
P="$HH/profiles/decision-call"
PY="$HH/hermes-agent/venv/bin/python"

# WHICH HERMES: the Desktop's backend is the one whose profiles a Desktop chat can open. On this Mac
# that is the BOX (the Desktop dials 127.0.0.1:9119, an ssh tunnel to the box's hermes-serve), so the
# profile must be installed there: `install.sh --box` copies the sources over and runs this script on
# the box. A Mac-only install serves `hermes -p decision-call chat` in a Mac terminal, nothing more.
if [[ "${1:-}" == "--box" ]]; then
  HOST="${BOX:-dgx-remote}"; D=".local/share/lucky-loop/decision-call-src"
  ssh -o BatchMode=yes "$HOST" "mkdir -p $D/hermes/plugins/decision-call $D/hermes/profiles/decision-call"
  scp -q "$REPO_ROOT/hermes/plugins/decision-call/__init__.py" "$REPO_ROOT/hermes/plugins/decision-call/plugin.yaml" \
    "$HOST:$D/hermes/plugins/decision-call/"
  scp -q "$HERE/SOUL.md" "$HERE/install.sh" "$HERE/profile_config.py" "$HOST:$D/hermes/profiles/decision-call/"
  ssh -o BatchMode=yes "$HOST" "bash ~/$D/hermes/profiles/decision-call/install.sh ${2:-}"
  exit $?
fi

if [[ "${1:-}" == "--check" ]]; then
  ls -la "$P/plugins/decision-call" 2>/dev/null || echo "plugin: not installed"
  (cd "$HH/hermes-agent" && HERMES_HOME="$P" "$PY" "$HERE/profile_config.py" check)
  exit $?
fi

HERMES_BIN="$(command -v hermes || echo "$HOME/.local/bin/hermes")"
[[ -x "$HERMES_BIN" ]] || { echo "no hermes binary found" >&2; exit 1; }
[[ -d "$P" ]] || "$HERMES_BIN" profile create decision-call --no-skills --no-alias \
  --description "The decision call: presents one needs-you card, discusses its effects, and records Karl's word only when he names it."

STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p "$P/backups/$STAMP"
for f in config.yaml SOUL.md; do [[ -f "$P/$f" ]] && cp -p "$P/$f" "$P/backups/$STAMP/$f"; done
[[ -d "$P/plugins/decision-call" ]] && cp -Rp "$P/plugins/decision-call" "$P/backups/$STAMP/plugin"

# The plugin, atomically (a half-copied plugin must never load).
mkdir -p "$P/plugins"
TMP="$(mktemp -d "$P/plugins/.decision-call.XXXX")"
cp "$REPO_ROOT/hermes/plugins/decision-call/plugin.yaml" "$REPO_ROOT/hermes/plugins/decision-call/__init__.py" "$TMP/"
rm -rf "$P/plugins/decision-call.old"
[[ -d "$P/plugins/decision-call" ]] && mv "$P/plugins/decision-call" "$P/plugins/decision-call.old"
mv "$TMP" "$P/plugins/decision-call"
rm -rf "$P/plugins/decision-call.old"

cp "$HERE/SOUL.md" "$P/SOUL.md.tmp" && mv "$P/SOUL.md.tmp" "$P/SOUL.md"

"$PY" "$HERE/profile_config.py" write "$HH/config.yaml" "$P/config.yaml" call
if [[ "$(uname)" == "Linux" ]]; then
  # On the box the writer's own clone IS the box clone: its "did the box take it" check reads this HEAD.
  touch "$P/.env"; chmod 600 "$P/.env"
  grep -v '^NYW_BOX_CMD=' "$P/.env" > "$P/.env.tmp" || true
  echo "NYW_BOX_CMD=git -C $HOME/brain rev-parse HEAD" >> "$P/.env.tmp"
  chmod 600 "$P/.env.tmp"; mv "$P/.env.tmp" "$P/.env"
fi
"$PY" "$P/plugins/decision-call/__init__.py" --selftest | tail -1
echo "installed. backup: $P/backups/$STAMP"
