"""Generate a decision-call profile's config.yaml, and prove what it resolves to.

Run with the Hermes venv's python (it imports the vendor's platform registry and resolver):

  profile_config.py write <main config.yaml> <out config.yaml> call|whatsapp
  profile_config.py check                       (HERMES_HOME = the profile) one line per platform

Shared by install.sh (the call) and whatsapp-switch.sh (switch 2), so the two profiles cannot drift.

* `platform_toolsets` names EVERY platform the vendor registry lists (hermes_cli.platforms), each
  set to `decision_call` alone. A platform left out falls back to its vendor default: on the box's
  build that was ~16-21 toolsets (terminal, file, browser, code_execution...) on api_server, cron,
  whatsapp and the rest (verifier HIGH 5, 2026-09-27).
* gbrain is copied from the main config with its READ-ONLY allowlist, minus `think` (its schema can
  write takes and spend model calls; verifier HIGH 3). A main config with no allowlist is refused.
* No memory, no user profile. TTS: an on-device engine (piper, kittentts, neutts) when this venv can
  import one, else `edge`, which sends the spoken text to Microsoft — the trade-off is in SWITCHES.md.
"""
from __future__ import annotations

import importlib.util
import os
import sys

import yaml

DENY_GBRAIN = {"think"}  # write-capable or spending tools never reach a call profile


def platforms() -> list:
    from hermes_cli.platforms import PLATFORMS  # the vendor's canonical registry
    return sorted(PLATFORMS)


def local_tts() -> str:
    """The first on-device engine this venv can import (the vendor supports all three), else edge."""
    for provider, module in (("piper", "piper"), ("kittentts", "kittentts"), ("neutts", "neutts")):
        if importlib.util.find_spec(module):
            return provider
    return "edge"


def write(main_path: str, out_path: str, kind: str) -> None:
    main = yaml.safe_load(open(main_path)) or {}
    gb = dict(((main.get("mcp_servers") or {}).get("gbrain") or {}))
    include = [t for t in (gb.get("tools") or {}).get("include") or [] if t not in DENY_GBRAIN]
    if not include:
        sys.exit("refused: the main config's gbrain server has no tools.include allowlist")
    gb["tools"] = {**(gb.get("tools") or {}), "include": include}
    cfg = {
        "model": main.get("model"),
        "plugins": {"enabled": ["decision-call"]},
        "platform_toolsets": {p: ["decision_call"] for p in platforms()},
        "mcp_servers": {"gbrain": gb},
        "memory": {"memory_enabled": False, "user_profile_enabled": False},
        "agent": {"max_turns": 40 if kind == "call" else 20, "reasoning_effort": "none"},
        "_config_version": main.get("_config_version", 45),
    }
    if kind == "call":
        cfg["terminal"] = {"backend": "local", "cwd": os.path.join(os.path.dirname(out_path), "workspace")}
        cfg["stt"] = {"enabled": True, "provider": "local", "local": {"model": "base"}}
        cfg["tts"] = {"provider": local_tts()}
        cfg["voice"] = {"voice_chat_mode": "chained"}
    tmp = out_path + ".tmp"
    with open(tmp, "w") as f:
        f.write("# Generated by lucky-loop hermes/profiles/decision-call/profile_config.py — edit the generator.\n")
        yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True)
    os.replace(tmp, out_path)
    print(f"config.yaml written: {len(cfg['platform_toolsets'])} platforms -> decision_call; "
          f"gbrain {len(include)} read-only tools; tts {cfg.get('tts', {}).get('provider', '-')}")


def check() -> int:
    from hermes_cli.config import load_config
    from hermes_cli.tools_config import _get_platform_tools
    cfg = load_config()
    bad = 0
    for p in platforms():
        ts = sorted(_get_platform_tools(cfg, p))
        extra = [t for t in ts if t not in ("decision_call", "gbrain")]
        bad += bool(extra)
        print(f"{'ok  ' if not extra else 'BAD '} {p:15} {len(ts)} toolsets: {', '.join(ts)}")
    inc = ((cfg.get("mcp_servers") or {}).get("gbrain") or {}).get("tools", {}).get("include", [])
    print(f"gbrain allowlist: {len(inc)} tools; think {'PRESENT' if 'think' in inc else 'absent'}")
    return 1 if bad or "think" in inc else 0


if __name__ == "__main__":
    a = sys.argv[1:]
    if a[:1] == ["write"] and len(a) == 4 and a[3] in ("call", "whatsapp"):
        write(a[1], a[2], a[3])
    elif a[:1] == ["check"]:
        sys.exit(check())
    else:
        print(__doc__)
        sys.exit(2)
