#!/usr/bin/env bash
# SWITCH 2 — WhatsApp answers. STAGED, OFF. The flip is Karl's (his phone pairs the number; the
# 09-10 "no WhatsApp" ruling stands until his word). See hermes/profiles/decision-call/SWITCHES.md.
#
# Runs ON THE BOX. Copy the three source files there first (from the Mac, in this repo):
#   hermes/profiles/decision-call/whatsapp-switch.sh push      (scp's the sources, then runs `stage` there)
#
#   whatsapp-switch.sh stage    install the decision-whatsapp profile, WhatsApp DISABLED; unit written, not enabled
#   whatsapp-switch.sh status   what is installed, whether it is on (never prints the number)
#   whatsapp-switch.sh flip     KARL: asks for his own number (hidden input), enables, then prints the pairing step
#   whatsapp-switch.sh off      stop + disable the unit, WHATSAPP_ENABLED=false (the number stays unless --forget)
#
# What the profile can do once on: the SAME three tools as the Desktop call (hermes/plugins/decision-call):
# read a card, read a word back, record it after an explicit yes in a later message (tier 3: a second yes),
# through the box's vault writer, doneBy "karl — whatsapp <word>". No terminal, no file, no web, no memory,
# no send tool: it answers only in the chat it was written in. Only Karl's number is allowlisted
# (dm_policy allowlist; groups disabled); another number gets nothing. Words only: a value (A4) is refused
# by the writer's value-shape check and by the call's rules.
#
# Why not the page's POST /answer: that route takes only requests carrying the Mac-only page key
# (slice 3's channel). Putting that key on the box would undo the channel. So WhatsApp writes through
# the same WRITER as verb (a) — needs-you-write, with the same id/word validation — not through its route.
set -euo pipefail
P_NAME=decision-whatsapp
UNIT=hermes-decision-whatsapp.service
SRC="${DECISION_CALL_SRC:-$HOME/.local/share/lucky-loop/decision-call-src}"
HH="$HOME/.hermes"
P="$HH/profiles/$P_NAME"
PY="$HH/hermes-agent/venv/bin/python"
HERMES="$HOME/.local/bin/hermes"
ENVF="$P/.env"

setenv() {  # setenv KEY VALUE — replace or append one line in the profile .env (0600)
  touch "$ENVF"; chmod 600 "$ENVF"
  local tmp; tmp="$(mktemp "$P/.env.XXXX")"
  grep -v "^$1=" "$ENVF" > "$tmp" || true
  printf '%s=%s\n' "$1" "$2" >> "$tmp"
  chmod 600 "$tmp"; mv "$tmp" "$ENVF"
}
getenv() { grep "^$1=" "$ENVF" 2>/dev/null | tail -1 | cut -d= -f2-; }

case "${1:-}" in
push)  # from the Mac
  HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; ROOT="$(cd "$HERE/../../.." && pwd)"
  HOST="${BOX:-dgx-remote}"
  ssh -o BatchMode=yes "$HOST" 'mkdir -p ~/.local/share/lucky-loop/decision-call-src'
  scp -q "$ROOT/hermes/plugins/decision-call/__init__.py" "$ROOT/hermes/plugins/decision-call/plugin.yaml" \
    "$HERE/SOUL.md" "$HERE/whatsapp-switch.sh" "$HOST:.local/share/lucky-loop/decision-call-src/"
  ssh -o BatchMode=yes "$HOST" 'bash ~/.local/share/lucky-loop/decision-call-src/whatsapp-switch.sh stage'
  ;;
stage)
  [[ -x "$HERMES" ]] || { echo "no hermes at $HERMES" >&2; exit 1; }
  [[ -d "$P" ]] || "$HERMES" profile create "$P_NAME" --no-skills --no-alias \
    --description "Decision answers over WhatsApp (staged OFF): one card, Karl's word read back, recorded only after an explicit yes."
  STAMP="$(date -u +%Y%m%dT%H%M%SZ)"; mkdir -p "$P/backups/$STAMP"
  for f in config.yaml SOUL.md .env; do [[ -f "$P/$f" ]] && cp -p "$P/$f" "$P/backups/$STAMP/"; done
  mkdir -p "$P/plugins/decision-call.new"
  cp "$SRC/__init__.py" "$SRC/plugin.yaml" "$P/plugins/decision-call.new/"
  rm -rf "$P/plugins/decision-call"; mv "$P/plugins/decision-call.new" "$P/plugins/decision-call"
  { cat "$SRC/SOUL.md"; printf '\n## Over WhatsApp\n\nYou are reached by text on WhatsApp, not by voice. Keep replies to a few lines. Start a\ncall only when Karl names a card or says "next". Never send anything first.\n'; } > "$P/SOUL.md"
  "$PY" - "$HH/config.yaml" "$P/config.yaml" <<'EOF'
import os, sys, yaml
main = yaml.safe_load(open(sys.argv[1])) or {}
gb = ((main.get("mcp_servers") or {}).get("gbrain") or {})
cfg = {
    "model": main.get("model"),
    "plugins": {"enabled": ["decision-call"]},
    # the toolset cut to the inbox: the call's three tools, nothing else, on every surface this profile has
    "platform_toolsets": {"whatsapp": ["decision_call"], "cli": ["decision_call"]},
    "memory": {"memory_enabled": False, "user_profile_enabled": False},
    "agent": {"max_turns": 20, "reasoning_effort": "none"},
    "_config_version": main.get("_config_version", 45),
}
if gb.get("tools", {}).get("include"):  # read-only allowlist only; a server without one is left out
    cfg["mcp_servers"] = {"gbrain": gb}
tmp = sys.argv[2] + ".tmp"
with open(tmp, "w") as f:
    f.write("# Generated by lucky-loop whatsapp-switch.sh stage — edit the script, not this file.\n")
    yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True)
os.replace(tmp, sys.argv[2])
EOF
  setenv WHATSAPP_ENABLED false
  setenv WHATSAPP_MODE bot                 # a separate number, not Karl's own chat
  setenv WHATSAPP_DM_POLICY allowlist      # only WHATSAPP_ALLOWED_USERS may write
  setenv WHATSAPP_GROUP_POLICY disabled
  setenv WHATSAPP_ALLOW_ALL_USERS false
  setenv DECISION_CALL_SURFACE whatsapp    # doneBy "karl — whatsapp <word>"
  setenv NYW_BOX_CMD "git -C $HOME/brain rev-parse HEAD"  # the writer runs on the box clone
  mkdir -p "$HOME/.config/systemd/user"
  cat > "$HOME/.config/systemd/user/$UNIT" <<EOF
[Unit]
Description=Hermes gateway for decision answers over WhatsApp (lucky-loop switch 2; OFF until Karl flips it)
After=network-online.target

[Service]
ExecStart=$PY -m hermes_cli.main -p $P_NAME gateway run
Environment=PATH=$HH/hermes-agent/venv/bin:$HH/hermes-agent/node_modules/.bin:/usr/bin:/bin
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
EOF
  systemctl --user daemon-reload
  "$PY" "$P/plugins/decision-call/__init__.py" --selftest | tail -1
  echo "staged OFF: profile $P_NAME, unit $UNIT written (not enabled). Backup: $P/backups/$STAMP"
  ;;
status)
  echo "profile: $([[ -d $P ]] && echo present || echo absent) · plugin: $([[ -f $P/plugins/decision-call/__init__.py ]] && echo installed || echo absent)"
  echo "WHATSAPP_ENABLED=$(getenv WHATSAPP_ENABLED) · mode=$(getenv WHATSAPP_MODE) · dm_policy=$(getenv WHATSAPP_DM_POLICY) · allowlist: $([[ -n "$(getenv WHATSAPP_ALLOWED_USERS)" ]] && echo 'one number set' || echo empty)"
  en="$(systemctl --user is-enabled $UNIT 2>/dev/null || true)"; ac="$(systemctl --user is-active $UNIT 2>/dev/null || true)"
  echo "unit: ${en:-absent} / ${ac:-inactive}"
  ;;
flip)
  [[ -t 0 ]] || { echo "refused: flip reads Karl's number from a terminal (hidden input); run it yourself on the box" >&2; exit 2; }
  [[ -f "$P/plugins/decision-call/__init__.py" ]] || { echo "not staged: run stage first" >&2; exit 2; }
  read -r -s -p "Your own WhatsApp number, digits only with country code (hidden; stays in $ENVF on this box): " NUM; echo
  [[ "$NUM" =~ ^[0-9]{8,15}$ ]] || { echo "refused: digits only, 8–15 of them" >&2; exit 2; }
  setenv WHATSAPP_ALLOWED_USERS "$NUM"; unset NUM
  setenv WHATSAPP_ENABLED true
  echo "enabled in the profile. Two steps left, both yours:"
  echo "  1. pair the SEPARATE number's phone:   $HERMES -p $P_NAME whatsapp     (scan the QR with that phone)"
  echo "  2. start it:                          systemctl --user enable --now $UNIT"
  echo "then from YOUR phone, message that number: next"
  ;;
off)
  systemctl --user disable --now "$UNIT" 2>/dev/null || true
  setenv WHATSAPP_ENABLED false
  [[ "${2:-}" == "--forget" ]] && setenv WHATSAPP_ALLOWED_USERS ""
  echo "off: unit stopped and disabled, WHATSAPP_ENABLED=false$([[ "${2:-}" == "--forget" ]] && echo ', number removed')"
  ;;
*) sed -n 2,20p "$0"; exit 2 ;;
esac
