import okrsJson from "@/data/okrs.json";
import ledgerJson from "@/data/ledger.json";
import deploysJson from "@/data/deploys.json";
import linksJson from "@/data/links.json";

/* Real data only — everything on /war derives from versioned JSON in /data
 * (see CLAUDE.md). No mock telemetry. */

/* ---------------------------------------------------------------------------
 * ONE-EDIT SWITCH — repo visibility.
 *
 * Karl's ruling (2026-07-28): the repo goes PUBLIC at launch, gated on a clean
 * all-refs secrets sweep. While this flag and the real GitHub visibility
 * disagree, every GitHub URL on this page — the links-rail row AND every
 * per-commit link in the Growth Ledger — is a public 404, so the two must
 * always move together.
 *
 * STATE 2026-08-05: FLIPPED, and the repo is public. The sequence, because the
 * rulings look contradictory in isolation: private at launch (07-30 ruling, so
 * launch day correctly shipped this `false`), then public on 08-05 gated on a
 * fresh sweep. `gitleaks detect --log-opts="--all"` (8.30.1) re-run at HEAD on
 * 08-05: 23 non-merge commits across all 27 refs-reachable commits, ZERO
 * findings.
 *
 * CORRECTION 2026-08-08. The flip was originally justified here with: "origin
 * carries exactly refs/heads/main, no tags and no mac-scaffold branch, so the
 * flip publishes nothing orphaned." That reasoning is WRONG and is recorded
 * rather than quietly deleted, because it is the seductive kind.
 * **Ref absence is not object absence.** The archive tag was pushed to origin
 * once before being deleted, and GitHub does not garbage-collect the objects it
 * received: both commits on the orphan mac-scaffold line still answer HTTP 200
 * from api.github.com today, fetchable by SHA. They were then actually read:
 * `576c1d6` is a stock create-next-app scaffold and `8719d10` is the old MOCK
 * War Room (a deterministic noise generator plus an on-call roster of invented
 * names). Non-sensitive, so the flip stands — but it stands on inspection of
 * the content, NOT on the ref check. Had a real secret been on that line, this
 * argument would have published it irreversibly.
 *
 * 2026-07-29 (Karl's ruling, executed, still binding): tag `archive/mac-scaffold-2026-07-22`
 * was DELETED from origin *before* the flip, so the orphan mac-scaffold line is
 * never published. On a public repo GitHub serves unreachable objects by SHA, so
 * deleting after the flip would have been effectively irreversible. Three copies
 * survive: local tag, the DGX mirror, and a verified bundle at
 * ~/Archive/lucky-loop/archive-mac-scaffold-2026-07-22.bundle.
 * DO NOT run `git push origin --tags` or `--follow-tags` — either recreates it,
 * now onto a public repo.
 * ------------------------------------------------------------------------- */
export const REPO_PUBLIC = true;

export type StatusRole = "good" | "warning" | "serious" | "critical";

export type KeyResult = {
  id: string;
  title: string;
  progress: number;
  note?: string;
  /* Pre-committed scoring rubric. Written BEFORE the work it scores, so the
   * launch-day number is certified against a fixed bar rather than self-awarded
   * after the fact. Rendered on /war so the bar is public, not private. */
  rubric?: string[];
};
export type Objective = {
  id: string;
  title: string;
  due: string;
  /** ISO day the objective actually reached 100%, when it has. */
  metOn?: string;
  keyResults: KeyResult[];
};
export type Commit = { sha: string; t: number; msg: string };
export type Deploy = { id?: string; t: number; url: string; target: string; sha: string };
export type LinkItem = {
  name: string;
  url: string;
  note?: string;
  /** Row is a github.com URL: hidden while REPO_PUBLIC is false. */
  requiresPublicRepo?: boolean;
};

export type LedgerEntry = {
  id: string;
  t: number;
  kind: "commit" | "deploy";
  title: string;
  detail?: string;
  href?: string;
};

/* data/ledger.json is regenerated by scripts/gen-ledger.mjs at prebuild; the
 * committed copy is the fallback when git history is unavailable or truncated.
 * `builtAt` and friends only exist on regenerated files, hence optional. */
type LedgerFile = {
  /** Timestamp of the newest commit in `commits`. */
  generatedAt: number;
  /** Wall clock at the build that produced this file. Not request time. */
  builtAt?: number;
  /** "git" when derived at build, "committed" when the fallback was kept. */
  source?: string;
  /** True when derived from a shallow checkout (history may be truncated). */
  shallow?: boolean;
  commits: Commit[];
};

const ledger = ledgerJson as LedgerFile;

const STEP_MS = 5 * 60 * 1000;

/* Request-scoped anchor on a 5-min grid: stable within a window, identical
 * between server render and hydration. Use it for "now"-relative chrome
 * (countdown, "x ago") only — never to window a build-time data set. */
export function currentAnchor(): number {
  return Math.floor(Date.now() / STEP_MS) * STEP_MS;
}

/** When the JSON rendered on this page was built. Not when it was requested. */
export function getBuildTime(): number {
  return ledger.builtAt ?? ledger.generatedAt;
}

export function getObjectives(): Objective[] {
  return okrsJson.objectives;
}

/* Rows with an empty URL never ship — a link rail that renders "add URL here"
 * to the public is a dead link (DoD #4). */
export function getLinks(): LinkItem[] {
  return (linksJson as LinkItem[]).filter(
    (l) => l.url.length > 0 && (REPO_PUBLIC || !l.requiresPublicRepo),
  );
}

export function getCommits(): Commit[] {
  return ledger.commits;
}

/* TRUE when the build that produced data/ledger.json ran on a checkout git
 * could not fully deepen (see scripts/gen-ledger.mjs). The commit list is then
 * a FLOOR, not the whole history, and every commit-derived number on the page
 * is a lower bound — so the page must say so rather than present a truncated
 * history as complete. Rendered by the "Commits · 7d" tile note and the Growth
 * Ledger heading. */
export function isLedgerTruncated(): boolean {
  return ledger.shallow === true;
}

/** Newest commit timestamp in the ledger — the anchor for commit windows. */
export function lastCommitAt(): number {
  return getCommits().reduce((max, c) => (c.t > max ? c.t : max), 0);
}

/** Recorded deploys, newest first. See scripts/sync-deploys.mjs for provenance. */
export function getDeploys(): Deploy[] {
  return (deploysJson as Deploy[]).slice().sort((a, b) => b.t - a.t);
}

export function getProductionDeploys(): Deploy[] {
  return getDeploys().filter((d) => d.target === "production");
}

const repoUrl = REPO_PUBLIC
  ? ((linksJson as LinkItem[]).find((l) => l.name === "GitHub")?.url ?? "")
  : "";

function bareHost(url: string): string {
  return url.replace(/^https?:\/\//, "");
}

export function getLedger(): LedgerEntry[] {
  const commits: LedgerEntry[] = getCommits().map((c) => ({
    id: `c-${c.sha}`,
    t: c.t,
    kind: "commit",
    title: c.msg,
    detail: c.sha.slice(0, 7),
    href: repoUrl ? `${repoUrl}/commit/${c.sha}` : undefined,
  }));
  /* PRODUCTION ONLY — one definition of "a deploy" across the whole page, so
   * the Growth Ledger can never disagree with the "Prod deploys" tile, and an
   * internal preview/feature-branch deploy can never surface publicly (DoD #4).
   *
   * Only the newest deploy is still serving; superseded deployment URLs are
   * not linked (they are auth-walled or gone — see DoD #4). */
  const all = getProductionDeploys();
  const live = all[0];
  const deploys: LedgerEntry[] = all.map((d) => ({
    id: `d-${d.id ?? d.sha}-${d.t}`,
    t: d.t,
    kind: "deploy",
    title: `Deployed to ${d.target}`,
    detail:
      d === live ? `${d.sha.slice(0, 7)} · live at ${bareHost(d.url)}` : `${d.sha.slice(0, 7)} · superseded`,
    href: d === live ? d.url : undefined,
  }));
  return [...commits, ...deploys].sort((a, b) => b.t - a.t);
}

/* Commits per UTC day for the `days`-day window ending on the NEWEST COMMIT,
 * oldest → newest.
 *
 * Deliberately not wall-clock anchored: the ledger is a build-time snapshot, so
 * a trailing window over "now" drains to zero days after the last build and
 * renders a flat line under a live clock. The tile label states the anchor. */
export function commitsPerDay(days = 7): number[] {
  const day = (x: number) => Math.floor(x / 86400000);
  const end = day(lastCommitAt());
  const counts = new Array<number>(days).fill(0);
  for (const c of getCommits()) {
    const idx = days - 1 - (end - day(c.t));
    if (idx >= 0 && idx < days) counts[idx] += 1;
  }
  return counts;
}

/* Whole UTC days between today and the due date, counted on the calendar —
 * not by dividing a millisecond span. Ceiling an end-of-day span read one high
 * all day (on Jul 30 it said "2" for a Jul 31 due date) and could never reach
 * zero, so the launch date itself would have rendered "1". A countdown that
 * cannot show zero is wrong on exactly the day it matters.
 *
 * Signed on purpose. This used to clamp at zero, which was the same bug one day
 * later: from Aug 1 to Aug 5 the War Room announced "TODAY · 0 days left" for a
 * Jul 31 date, five days after the fact. Past-due days come back negative;
 * dueState() decides what the page says about them. */
export function daysUntil(dateISO: string, anchor: number): number {
  const [y, m, d] = dateISO.split("-").map(Number);
  const dueDay = Math.floor(Date.UTC(y, m - 1, d) / 86400000);
  const today = Math.floor(anchor / 86400000);
  return dueDay - today;
}

/* What the page should SAY about a due date — derived from the date plus the
 * objective's own progress, never from a hand-written status string that can
 * rot. Completion outranks the calendar: an objective at 100% reads as met
 * whether the date has passed or not, and a date that passes unmet says so. */
export type DueState =
  | { kind: "ahead"; days: number }
  | { kind: "due-today" }
  | { kind: "met"; metOn?: string }
  | { kind: "overdue"; days: number };

export function dueState(o: Objective, anchor: number): DueState {
  const days = daysUntil(o.due, anchor);
  if (objectiveProgress(o) >= 1) return { kind: "met", metOn: o.metOn };
  if (days > 0) return { kind: "ahead", days };
  if (days === 0) return { kind: "due-today" };
  return { kind: "overdue", days: -days };
}

/** "2026-07-31" → "07/31" — the date form used across the OKR surfaces. */
export function mmdd(dateISO: string): string {
  return dateISO.slice(5).replace("-", "/");
}

export function objectiveProgress(o: Objective): number {
  if (o.keyResults.length === 0) return 0;
  return o.keyResults.reduce((s, kr) => s + kr.progress, 0) / o.keyResults.length;
}
