import okrsJson from "@/data/okrs.json";
import ledgerJson from "@/data/ledger.json";
import deploysJson from "@/data/deploys.json";
import linksJson from "@/data/links.json";
import loopStatusJson from "@/data/loop-status.json";
import failureStatusJson from "@/data/failure-status.json";
import agentsJson from "@/data/agents.json";
import agentLivenessJson from "@/data/agent-liveness.json";

/* Real data only — everything on /war derives from versioned JSON in /data
 * (see CLAUDE.md). No mock telemetry. */

/* ---------------------------------------------------------------------------
 * ONE-EDIT SWITCH — repo visibility.
 *
 * Karl's ruling (2026-07-28): the repo goes PUBLIC at launch, gated on a clean
 * all-refs secrets sweep. While this flag and the real GitHub visibility
 * disagree, every GitHub URL on this page — the links-rail row AND every
 * per-commit link in the Growth Ledger — is a public 404, so the two must
 * always move together.
 *
 * STATE 2026-08-05: FLIPPED, and the repo is public. The sequence, because the
 * rulings look contradictory in isolation: private at launch (07-30 ruling, so
 * launch day correctly shipped this `false`), then public on 08-05 gated on a
 * fresh sweep. `gitleaks detect --log-opts="--all"` (8.30.1) re-run at HEAD on
 * 08-05: 23 non-merge commits across all 27 refs-reachable commits, ZERO
 * findings.
 *
 * CORRECTION 2026-08-08. The flip was originally justified here with: "origin
 * carries exactly refs/heads/main, no tags and no mac-scaffold branch, so the
 * flip publishes nothing orphaned." That reasoning is WRONG and is recorded
 * rather than quietly deleted, because it is the seductive kind.
 * **Ref absence is not object absence.** The archive tag was pushed to origin
 * once before being deleted, and GitHub does not garbage-collect the objects it
 * received: both commits on the orphan mac-scaffold line still answer HTTP 200
 * from api.github.com today, fetchable by SHA. They were then actually read:
 * `576c1d6` is a stock create-next-app scaffold and `8719d10` is the old MOCK
 * War Room (a deterministic noise generator plus an on-call roster of invented
 * names). Non-sensitive, so the flip stands — but it stands on inspection of
 * the content, NOT on the ref check. Had a real secret been on that line, this
 * argument would have published it irreversibly.
 *
 * 2026-07-29 (Karl's ruling, executed, still binding): tag `archive/mac-scaffold-2026-07-22`
 * was DELETED from origin *before* the flip, so the orphan mac-scaffold line is
 * never published. On a public repo GitHub serves unreachable objects by SHA, so
 * deleting after the flip would have been effectively irreversible. Three copies
 * survive: local tag, the DGX mirror, and a verified bundle at
 * ~/Archive/lucky-loop/archive-mac-scaffold-2026-07-22.bundle.
 * DO NOT run `git push origin --tags` or `--follow-tags` — either recreates it,
 * now onto a public repo.
 * ------------------------------------------------------------------------- */
export const REPO_PUBLIC = true;

export type StatusRole = "good" | "warning" | "serious" | "critical";

export type KeyResult = {
  id: string;
  title: string;
  progress: number;
  note?: string;
  /* Pre-committed scoring rubric. Written BEFORE the work it scores, so the
   * launch-day number is certified against a fixed bar rather than self-awarded
   * after the fact. Rendered by OkrPanel (collapsed) so the bar is public, not
   * private — this sentence asserted that for two weeks before it was true. */
  rubric?: string[];
};
export type Objective = {
  id: string;
  title: string;
  due: string;
  /** ISO day the objective actually reached 100%, when it has. */
  metOn?: string;
  keyResults: KeyResult[];
};
export type Commit = { sha: string; t: number; msg: string };
export type Deploy = { id?: string; t: number; url: string; target: string; sha: string };
export type LinkItem = {
  name: string;
  url: string;
  note?: string;
  /** Row is a github.com URL: hidden while REPO_PUBLIC is false. */
  requiresPublicRepo?: boolean;
};

export type LedgerEntry = {
  id: string;
  t: number;
  kind: "commit" | "deploy";
  title: string;
  detail?: string;
  href?: string;
};

/* data/ledger.json is regenerated by scripts/gen-ledger.mjs at prebuild; the
 * committed copy is the fallback when git history is unavailable or truncated.
 * `builtAt` and friends only exist on regenerated files, hence optional. */
type LedgerFile = {
  /** Timestamp of the newest commit in `commits`. */
  generatedAt: number;
  /** Wall clock at the build that produced this file. Not request time. */
  builtAt?: number;
  /** "git" when derived at build, "committed" when the fallback was kept. */
  source?: string;
  /** True when derived from a shallow checkout (history may be truncated). */
  shallow?: boolean;
  commits: Commit[];
};

const ledger = ledgerJson as LedgerFile;

const STEP_MS = 5 * 60 * 1000;

/* Request-scoped anchor on a 5-min grid: stable within a window, identical
 * between server render and hydration. Use it for "now"-relative chrome
 * (countdown, "x ago") only — never to window a build-time data set. */
export function currentAnchor(): number {
  return Math.floor(Date.now() / STEP_MS) * STEP_MS;
}

/** When the JSON rendered on this page was built. Not when it was requested. */
export function getBuildTime(): number {
  return ledger.builtAt ?? ledger.generatedAt;
}

export function getObjectives(): Objective[] {
  return okrsJson.objectives;
}

/* Rows with an empty URL never ship — a link rail that renders "add URL here"
 * to the public is a dead link (DoD #4). */
export function getLinks(): LinkItem[] {
  return (linksJson as LinkItem[]).filter(
    (l) => l.url.length > 0 && (REPO_PUBLIC || !l.requiresPublicRepo),
  );
}

export function getCommits(): Commit[] {
  return ledger.commits;
}

/* TRUE when the build that produced data/ledger.json ran on a checkout git
 * could not fully deepen (see scripts/gen-ledger.mjs). The commit list is then
 * a FLOOR, not the whole history, and every commit-derived number on the page
 * is a lower bound — so the page must say so rather than present a truncated
 * history as complete. Rendered by the "Commits · 7d" tile note and the Growth
 * Ledger heading. */
export function isLedgerTruncated(): boolean {
  return ledger.shallow === true;
}

/* TRUE when the ledger shipped in this build was actually derived from git.
 *
 * gen-ledger.mjs already wrote this field and NOTHING read it. That is how
 * /war came to stamp "Data built Aug 8, 11:13 UTC from git + Vercel · last
 * commit 8d ago" on a page that simultaneously showed today's commit deployed:
 * the script writes `builtAt: Date.now()` unconditionally, but keeps the
 * COMMITTED commit list whenever the derive loses (a shallow Vercel checkout it
 * cannot deepen without credentials). The build stamp was always fresh and the
 * data behind it could be arbitrarily old.
 *
 * `shallow` could not cover this: the refusal path leaves it at its `false`
 * initialiser, so the one caveat the page could render is switched OFF exactly
 * on the path that produces stale data. Truncation had a UI; staleness had
 * none. This is that missing state. */
export function isLedgerFromGit(): boolean {
  return ledger.source !== "committed";
}

/** When the newest commit in this ledger landed — i.e. how current it is. */
export function ledgerAsOf(): number {
  return ledger.generatedAt;
}

/** Newest commit timestamp in the ledger — the anchor for commit windows. */
export function lastCommitAt(): number {
  return getCommits().reduce((max, c) => (c.t > max ? c.t : max), 0);
}

/** Recorded deploys, newest first. See scripts/sync-deploys.mjs for provenance. */
export function getDeploys(): Deploy[] {
  return (deploysJson as Deploy[]).slice().sort((a, b) => b.t - a.t);
}

export function getProductionDeploys(): Deploy[] {
  return getDeploys().filter((d) => d.target === "production");
}

const repoUrl = REPO_PUBLIC
  ? ((linksJson as LinkItem[]).find((l) => l.name === "GitHub")?.url ?? "")
  : "";

function bareHost(url: string): string {
  return url.replace(/^https?:\/\//, "");
}

export function getLedger(): LedgerEntry[] {
  const commits: LedgerEntry[] = getCommits().map((c) => ({
    id: `c-${c.sha}`,
    t: c.t,
    kind: "commit",
    title: c.msg,
    detail: c.sha.slice(0, 7),
    href: repoUrl ? `${repoUrl}/commit/${c.sha}` : undefined,
  }));
  /* PRODUCTION ONLY — one definition of "a deploy" across the whole page, so
   * the Growth Ledger can never disagree with the "Prod deploys" tile, and an
   * internal preview/feature-branch deploy can never surface publicly (DoD #4).
   *
   * Only the newest deploy is still serving; superseded deployment URLs are
   * not linked (they are auth-walled or gone — see DoD #4). */
  const all = getProductionDeploys();
  const live = all[0];
  const deploys: LedgerEntry[] = all.map((d) => ({
    id: `d-${d.id ?? d.sha}-${d.t}`,
    t: d.t,
    kind: "deploy",
    title: `Deployed to ${d.target}`,
    detail:
      d === live ? `${d.sha.slice(0, 7)} · live at ${bareHost(d.url)}` : `${d.sha.slice(0, 7)} · superseded`,
    href: d === live ? d.url : undefined,
  }));
  return [...commits, ...deploys].sort((a, b) => b.t - a.t);
}

/* Commits per UTC day for the `days`-day window ending on the NEWEST COMMIT,
 * oldest → newest.
 *
 * Deliberately not wall-clock anchored: the ledger is a build-time snapshot, so
 * a trailing window over "now" drains to zero days after the last build and
 * renders a flat line under a live clock. The tile label states the anchor. */
export function commitsPerDay(days = 7): number[] {
  const day = (x: number) => Math.floor(x / 86400000);
  const end = day(lastCommitAt());
  const counts = new Array<number>(days).fill(0);
  for (const c of getCommits()) {
    const idx = days - 1 - (end - day(c.t));
    if (idx >= 0 && idx < days) counts[idx] += 1;
  }
  return counts;
}

/* Whole UTC days between today and the due date, counted on the calendar —
 * not by dividing a millisecond span. Ceiling an end-of-day span read one high
 * all day (on Jul 30 it said "2" for a Jul 31 due date) and could never reach
 * zero, so the launch date itself would have rendered "1". A countdown that
 * cannot show zero is wrong on exactly the day it matters.
 *
 * Signed on purpose. This used to clamp at zero, which was the same bug one day
 * later: from Aug 1 to Aug 5 the War Room announced "TODAY · 0 days left" for a
 * Jul 31 date, five days after the fact. Past-due days come back negative;
 * dueState() decides what the page says about them. */
export function daysUntil(dateISO: string, anchor: number): number {
  const [y, m, d] = dateISO.split("-").map(Number);
  const dueDay = Math.floor(Date.UTC(y, m - 1, d) / 86400000);
  const today = Math.floor(anchor / 86400000);
  return dueDay - today;
}

/* What the page should SAY about a due date — derived from the date plus the
 * objective's own progress, never from a hand-written status string that can
 * rot. Completion outranks the calendar: an objective at 100% reads as met
 * whether the date has passed or not, and a date that passes unmet says so. */
export type DueState =
  | { kind: "ahead"; days: number }
  | { kind: "due-today" }
  | { kind: "met"; metOn?: string }
  | { kind: "overdue"; days: number };

export function dueState(o: Objective, anchor: number): DueState {
  const days = daysUntil(o.due, anchor);
  if (objectiveProgress(o) >= 1) return { kind: "met", metOn: o.metOn };
  if (days > 0) return { kind: "ahead", days };
  if (days === 0) return { kind: "due-today" };
  return { kind: "overdue", days: -days };
}

/** "2026-07-31" → "07/31" — the date form used across the OKR surfaces. */
export function mmdd(dateISO: string): string {
  return dateISO.slice(5).replace("-", "/");
}

/* Clamped to [0,1]. Unclamped, a KR at 1.5 beside one at 0.5 averaged to
 * exactly 1.0, so dueState() returned "met" and the hero tile read SHIPPED
 * while the panel underneath showed a key result at 50% — and the same raw
 * value reached the meter as a 150% CSS width and aria-valuenow=150 against
 * aria-valuemax=100. A number that can exceed its own maximum is not a
 * progress value. */
export function objectiveProgress(o: Objective): number {
  if (o.keyResults.length === 0) return 0;
  const mean = o.keyResults.reduce((s, kr) => s + kr.progress, 0) / o.keyResults.length;
  return Math.min(1, Math.max(0, mean));
}


/* ---------------------------------------------------------------------------
 * The loop's own state.
 *
 * Written by `npm run sync:loop` from the DGX, which is the only place these
 * facts exist. Before this panel, the site could say what the loop had DONE
 * (the committed passes) and nothing at all about whether it was still alive —
 * so a healthy timer firing every ten minutes over an empty queue looked
 * identical to a dead box, for ten days.
 *
 * loopState() is dueState()'s shape on purpose: a discriminated kind the render
 * site switches on, so every boundary is a state the panel can draw rather than
 * a number it clamps. The boundaries here are: no file, a snapshot too old to
 * make claims from, a stopped scheduler, a failure newer than the last success,
 * an empty queue, and a fed one. Six, all reachable.
 * ------------------------------------------------------------------------- */

export type LoopStatus = {
  schema: number;
  syncedAt: string;
  loop: {
    lastPassAt: string | null;
    passCount: number;
    docTypes: string[];
    queueDepth: number | null;
    processedCount: number | null;
    scheduler: { active: boolean; lastTickAt: string | null; nextTickAt: string | null };
    lastTick: { exit: number | null; meaning: string; at: string | null };
    lastFailureAt: string | null;
  };
};

/* A snapshot older than this can still be SHOWN — it cannot be used to assert
 * what the queue holds right now. 24h because the sync is a human action, not a
 * feed; the exact age is always rendered beside it so a reader can judge for
 * themselves rather than trusting this threshold. */
export const LOOP_SNAPSHOT_STALE_MS = 24 * 60 * 60 * 1000;

export type LoopStateKind =
  | "unknown"
  | "stale"
  | "down"
  | "failing"
  | "starving"
  | "working";

export type LoopState = {
  kind: LoopStateKind;
  role: StatusRole;
  label: string;
  detail: string;
};

export function getLoopStatus(): LoopStatus | null {
  const raw = loopStatusJson as unknown as LoopStatus;
  if (!raw || typeof raw.syncedAt !== "string" || !raw.loop) return null;
  return raw;
}

export function loopState(status: LoopStatus | null, anchor: number): LoopState {
  if (!status) {
    return {
      kind: "unknown",
      role: "warning",
      label: "Unknown",
      detail: "No status snapshot has been committed. Run `npm run sync:loop`.",
    };
  }

  const { loop } = status;
  const age = anchor - Date.parse(status.syncedAt);

  /* Staleness is checked BEFORE health, deliberately. Every state below is a
   * claim about the loop right now, and a day-old snapshot cannot support one.
   * Saying "starving" from stale data is the same class of error as the
   * countdown that clamped at zero: an assertion the data no longer licenses. */
  if (!Number.isFinite(age) || age > LOOP_SNAPSHOT_STALE_MS) {
    return {
      kind: "stale",
      role: "warning",
      label: "Snapshot stale",
      detail:
        "These numbers were true when the snapshot was taken and cannot be read as current. Sync to refresh.",
    };
  }

  if (!loop.scheduler?.active) {
    return {
      kind: "down",
      role: "critical",
      label: "Scheduler stopped",
      detail: "The timer is not active. No pass will run until it is started again.",
    };
  }

  /* Health is the LAST TICK's exit code, not the last failure's age.
   *
   * The first version of this compared lastFailureAt to lastPassAt, and on the
   * real data that read "Last run failed" — because the Aug 11 failure landed
   * 27 minutes after the Aug 11 pass. Around fourteen hundred successful ticks
   * have run since. The last run did not fail; it idled, correctly. Comparing a
   * failure against the last SUCCESS instead of against the last EVENT makes a
   * fault permanent the moment it happens after the newest success, which for a
   * queue that is usually empty is almost always.
   *
   * exit 3 is the only code that means failure (0 converged, 2 already
   * recorded, 4 idle). A failure stamped after the last tick counts too, since
   * a unit that dies before writing its exit leaves the log as the only trace. */
  const failedAt = loop.lastFailureAt ? Date.parse(loop.lastFailureAt) : NaN;
  const tickAt = loop.lastTick?.at ? Date.parse(loop.lastTick.at) : NaN;
  const tickFailed = loop.lastTick?.exit === 3;
  const failureAfterLastTick =
    Number.isFinite(failedAt) && (!Number.isFinite(tickAt) || failedAt > tickAt);
  if (tickFailed || failureAfterLastTick) {
    return {
      kind: "failing",
      role: "serious",
      label: "Last run failed",
      detail: "The most recent tick did not complete. The failure log lives on the loop host.",
    };
  }

  /* The state this project actually lives in. It is NOT "good" — nothing is
   * being produced — and it is NOT "critical" — nothing is broken. A machine
   * that works and is unfed needs its own word, or the dashboard rounds it to
   * one of the two lies either side of it. */
  if (loop.queueDepth === 0) {
    return {
      kind: "starving",
      role: "warning",
      label: "Idle — nothing queued",
      detail: "The scheduler is healthy and the queue is empty. Idle ticks are correct, not a fault.",
    };
  }

  if (typeof loop.queueDepth === "number" && loop.queueDepth > 0) {
    return {
      kind: "working",
      role: "good",
      label: "Fed — work queued",
      detail: "Documents are waiting; the next tick will take one.",
    };
  }

  return {
    kind: "unknown",
    role: "warning",
    label: "Queue unreadable",
    detail: "The snapshot carries no queue depth. The host answered, but not with a count.",
  };
}

/** Whole days between two instants, floored. Used for "last pass N days ago". */
export function daysBetween(fromISO: string | null, anchor: number): number | null {
  if (!fromISO) return null;
  const t = Date.parse(fromISO);
  if (!Number.isFinite(t)) return null;
  return Math.floor((anchor - t) / 86_400_000);
}

/* The scheduler's interval, derived from the two stamps the snapshot already
 * carries. Rendering "next tick" alone was wrong: the snapshot is a manual
 * sample, so by the time anyone reads it the "next" tick is usually in the
 * past, and the panel cheerfully printed "next tick 20m ago". Cadence stays
 * true however old the sample is; the next tick is shown only while it is
 * genuinely still ahead. */
export function tickIntervalMs(status: LoopStatus | null): number | null {
  const last = status?.loop?.scheduler?.lastTickAt;
  const next = status?.loop?.scheduler?.nextTickAt;
  if (!last || !next) return null;
  const ms = Date.parse(next) - Date.parse(last);
  return Number.isFinite(ms) && ms > 0 ? ms : null;
}

/* ---------------------------------------------------------------------------
 * The roster.
 *
 * Six things act on this project and until now no surface named them. Karl
 * could not answer "who works for me, what may each one do, and what may it
 * never do" from anywhere — the answers lived in a CLAUDE.md paragraph, a
 * systemd unit, a workflow file and a chat thread.
 *
 * This is a CHARTER, not a monitor. Every row states a boundary, and the
 * boundaries are the point: a roster that listed capabilities without limits
 * would be a sales page for the fleet. Liveness is asserted only where it can
 * be DERIVED — see heraldGate() — because a hand-typed "last seen" rots into
 * exactly the lie the canvas told for two weeks.
 * ------------------------------------------------------------------------- */

/** DERIVED liveness, never declared. `unknown` means NOT INSTRUMENTED — there is
 *  no evidence path for that agent — which is neither live nor failed, and is
 *  never a fallback for a value we could not derive. Produced by
 *  scripts/sync-agent-liveness.mjs into data/agent-liveness.json. */
export type AgentState = "live" | "idle" | "unknown";

export type AgentLiveness = { state: AgentState; evidence: string };

/** Present only on agents this repo GENERATES onto a host (scripts/gen-agents.mjs).
 *  Its absence is meaningful: those rows are describing something the repo does
 *  not deploy — CI, a cloud agent, a human at a terminal. */
export type AgentHermes = {
  host: string;
  profile: string;
  displayName: string;
  model: string;
  baseUrl: string;
  contextLength: number;
  template: string;
  hooks?: string[];
  staging?: { available: boolean; repoPath: string | null; reason: string; sayExactly?: string };
};

export type Agent = {
  id: string;
  name: string;
  runtime: string;
  cadence: string;
  since: string;
  gate?: { minPasses: number; minDocTypes: number };
  does: string;
  /* A string on hand-written rows; an array on generated ones, where each entry
   * is one line of the agent's own "## Never" section. Same source, two
   * renderings — the roster and the soul cannot disagree about the limits. */
  cannot: string | string[];
  hermes?: AgentHermes;
};

export function getAgents(): Agent[] {
  return (agentsJson as { agents: Agent[] }).agents;
}

/** Derived liveness for the roster, with the sample time it was true at.
 *
 *  The roster itself carries NO liveness field. It used to: a hand-typed
 *  `state` that read `live` for two agents which have no evidence path at all.
 *  An agent with no deriver reports `unknown`, and the UI must render that as
 *  "not instrumented" rather than as a state. */
export function getAgentLiveness(): {
  syncedAt: string;
  derivedCount: number;
  totalCount: number;
  of: (id: string) => AgentLiveness;
} {
  const raw = agentLivenessJson as {
    syncedAt: string;
    derivedCount: number;
    totalCount: number;
    liveness: Record<string, AgentLiveness>;
  };
  return {
    syncedAt: raw.syncedAt,
    derivedCount: raw.derivedCount,
    totalCount: raw.totalCount,
    of: (id) =>
      raw.liveness[id] ?? { state: "unknown", evidence: "no deriver defined for this agent id" },
  };
}

/** The limits, always as a list. A single prose string is one limit. */
export function agentLimits(agent: Agent): string[] {
  return Array.isArray(agent.cannot) ? agent.cannot : [agent.cannot];
}

/** A gated agent's distance from its own unlock, read off the loop's record
 *  rather than declared. If the gate is met the roster says so, and whoever
 *  wakes the agent does it against a number, not a feeling. */
export function heraldGate(
  agent: Agent,
  status: LoopStatus | null,
): { met: boolean; passes: number; docTypes: number; needPasses: number; needDocTypes: number } | null {
  if (!agent.gate) return null;
  const passes = status?.loop?.passCount ?? 0;
  const docTypes = status?.loop?.docTypes?.length ?? 0;
  return {
    met: passes >= agent.gate.minPasses && docTypes >= agent.gate.minDocTypes,
    passes,
    docTypes,
    needPasses: agent.gate.minPasses,
    needDocTypes: agent.gate.minDocTypes,
  };
}


/* ---------------------------------------------------------------------------
 * THE FAILURE CHANNEL
 *
 * The 2026-08-19 audit recorded that failures are invisible to every UI, and it
 * stayed true until 2026-08-28. The cost of that was not theoretical: a launchd
 * job had been failing on every retry for weeks with its own error log pointed
 * at an unmounted volume, and the route to the loop host had died 59 times,
 * reaping the Desktop's socket 33 times in three days. Every surface said the
 * system was fine, because every surface only rendered successes.
 *
 * failureState() follows loopState() which follows dueState(): a discriminated
 * kind the render site switches on. The boundaries that must each be a DRAWABLE
 * state rather than a clamped number are — no file at all, a snapshot too old
 * to assert from, genuinely nothing failing, and something failing now. The
 * third one is the one that is easy to get wrong: "zero failures" and "we have
 * not looked" must never render the same, which is exactly the bug
 * loop-status.json was created to kill on the other side of the house.
 * ------------------------------------------------------------------------- */

export type FailureStatus = {
  schema: number;
  syncedAt: string;
  windowDays: number;
  loopHost: {
    orphanReaps: { window: number; today: number; distinctSessions: number };
    serviceRestarts: number | null;
    failedUnits: { named: string[]; otherCount: number };
    deadMan: { entries: number; lastAt: string | null };
  };
  workstation: { failingJobs: number; kinds: string[]; routeDeaths: number | null };
};

export type FailureStateKind = "unknown" | "stale" | "quiet" | "degrading" | "failing";

export type FailureState = {
  kind: FailureStateKind;
  role: StatusRole;
  label: string;
  detail: string;
};

export function getFailureStatus(): FailureStatus | null {
  const raw = failureStatusJson as unknown as FailureStatus;
  if (!raw || typeof raw.syncedAt !== "string" || !raw.loopHost) return null;
  return raw;
}

/* Total live failure signals in the snapshot. Route deaths are excluded on
 * purpose: they are a LIFETIME count from an unrotated log, so adding them
 * would make the number grow forever and never return to zero — a meter that
 * can only rise is a meter nobody reads. They render as their own figure. */
export function failureSignals(s: FailureStatus | null): number {
  if (!s) return 0;
  return (
    s.loopHost.failedUnits.named.length +
    s.loopHost.failedUnits.otherCount +
    s.workstation.failingJobs +
    (s.loopHost.orphanReaps.today > 0 ? 1 : 0)
  );
}

export function failureState(s: FailureStatus | null, anchor: number): FailureState {
  if (!s) {
    return {
      kind: "unknown",
      role: "warning",
      label: "Not sampled",
      detail:
        "No failure snapshot is committed, so this panel can say nothing. " +
        "That is not the same as nothing being wrong. Run `npm run sync:failures`.",
    };
  }

  const age = anchor - Date.parse(s.syncedAt);
  if (Number.isFinite(age) && age > LOOP_SNAPSHOT_STALE_MS) {
    return {
      kind: "stale",
      role: "warning",
      label: "Snapshot stale",
      detail:
        "The last sample is over a day old. Everything below was true then; " +
        "nothing here is a claim about now.",
    };
  }

  const n = failureSignals(s);
  if (n === 0) {
    return {
      kind: "quiet",
      role: "good",
      label: "Nothing failing",
      detail:
        "No failed unit, no failing workstation job, and no socket reaped today " +
        "as at the sample below. The empty case, reported — not an absence of looking.",
    };
  }

  /* Reaps alone are degradation: the route is flapping and the Desktop keeps
   * recovering. A failed unit or a stuck job is something that is not
   * recovering, and outranks it. */
  const hard = s.loopHost.failedUnits.named.length + s.loopHost.failedUnits.otherCount + s.workstation.failingJobs;
  if (hard === 0) {
    return {
      kind: "degrading",
      role: "warning",
      label: "Route degrading",
      detail:
        `The socket to the loop host was reaped ${s.loopHost.orphanReaps.today} time(s) today. ` +
        "Nothing is stuck — the connection keeps dropping and recovering.",
    };
  }

  return {
    kind: "failing",
    role: "critical",
    label: hard === 1 ? "1 thing failing" : `${hard} things failing`,
    detail:
      "At least one unit or scheduled job is failing and not recovering on its own. " +
      "A retry loop is not a fix.",
  };
}
